// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MiddlewareTester is an autogenerated mock type for the MiddlewareTester type
type MiddlewareTester struct {
	mock.Mock
}

// CallThis provides a mock function with given fields: _a0
func (_m *MiddlewareTester) CallThis(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMiddlewareTester creates a new instance of MiddlewareTester. It also registers a cleanup function to assert the mocks expectations.
func NewMiddlewareTester(t testing.TB) *MiddlewareTester {
	mock := &MiddlewareTester{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
