// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RouterWrapperTester is an autogenerated mock type for the RouterWrapperTester type
type RouterWrapperTester struct {
	mock.Mock
}

// CalledIt provides a mock function with given fields:
func (_m *RouterWrapperTester) CalledIt() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
