// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RouterWrapperTester is an autogenerated mock type for the RouterWrapperTester type
type RouterWrapperTester struct {
	mock.Mock
}

// CalledIt provides a mock function with given fields:
func (_m *RouterWrapperTester) CalledIt() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewRouterWrapperTester creates a new instance of RouterWrapperTester. It also registers a cleanup function to assert the mocks expectations.
func NewRouterWrapperTester(t testing.TB) *RouterWrapperTester {
	mock := &RouterWrapperTester{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
